### ISSUE TITLE
create activity diagrams

### ISSUE THREAD

**Issue by lmschw** [lmschw/StressFreeLearningPlatform#5]
based on the use case diagram and the requirements

**Comment by easyadin** [comment]
Currently working on the activity diagram

**Comment by lmschw** [comment]
@easyadin I've copied your diagram into a separate file - it's still in the use case. Could you delete the tab once you made sure that everything is copied fine? Thanks.

**Comment by lmschw** [comment]
activity diagram 2 (Activity Diagram: Researcher looking for study participants and funding) done and added to drive

**Comment by lmschw** [comment]
activity diagram 3 (Activity Diagram: Parent wants to schedule test for child) done and added to drive

**Comment by lmschw** [comment]
activity diagram 6 (Activity Diagram: Tester wanting to do a test and send a generated test report) done and added to drive
